definitions:
  tags: &common_tags
    - "remote"
    - "eks"
    - "{{ get-commit-hash.stdout }}"
  work_pool: &common_work_pool
    name: "kubernetes"
    job_variables:
      image: "{{ image }}"


deployments:
- name: "default"
  tags: *common_tags
  entrypoint: "flows/hello.py:hello"
  work_pool: *common_work_pool

- name: "arthur"
  tags: *common_tags
  entrypoint: "flows/hello.py:hello"
  parameters:
    name: "Arthur"
  work_pool: *common_work_pool

- name: "default"
  tags: *common_tags
  entrypoint: "flows/hello.py:hello_parallel"
  work_pool: *common_work_pool

- name: "databricks_execute"
  tags: *common_tags
  entrypoint: "flows/databricks_api_exec.py:databricks_job_submit"
  parameters:
    databricks_credentials_block_name: "qa-databricks-repo"
    job_id: "157107892089699"
  work_pool: *common_work_pool