###
### A complete description of a Prefect Deployment for flow 'databricks-job-submit'
###
name: databricks_github
description: null
version: 00479ba25be10f7f9d4ba1b56bcbd3c0
# The work queue that will handle this deployment's runs
work_queue_name: default
work_pool_name: kubernetes
tags: []
parameters:
    databricks_credentials_block_name: "qa-databricks-repo"
    job_id: "157107892089699"
schedule:
    interval: 600
    anchor_date: '2023-08-17T03:51:53.048975+00:00'
    timezone: UTC
is_schedule_active: null
infra_overrides:
  image: 'jllsbxprefect.azurecr.io/jllsbxprefect/prefect_monorepo'
infrastructure:
  type: docker-container
  env: {}
  labels: {}
  name: null
  command: null
  image: prefecthq/prefect:2.11.3-python3.9
  image_pull_policy: null
  image_registry: null
  networks: []
  network_mode: null
  auto_remove: false
  volumes: []
  stream_output: true
  memswap_limit: null
  mem_limit: null
  privileged: false
  block_type_slug: docker-container
  _block_type_slug: docker-container

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: databricks-job-submit
manifest_path: null
storage: null
path: /opt/prefect/prefect_acr/flows
entrypoint: flows\databricks_api_exec.py:databricks_job_submit
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    databricks_credentials_block_name:
      title: databricks_credentials_block_name
      position: 0
      type: string
    job_id:
      title: job_id
      position: 1
  required:
  - databricks_credentials_block_name
  - job_id
  definitions: null
timestamp: '2023-08-17T08:08:28.312139+00:00'
triggers: []
